### ISSUE TITLE
[기능] Todo 조회

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/todo-list-with-vue#2]
### 개요
> Todo 목록을 조회할 수 있도록 한다.

### 요구사항
- 등록된 Todo를 목록 형태로 보여준다. 
- 날짜, 상태, 제목, 설명이 보여야 한다.

### 해야 할 일
- [x] Todo Item 컴포넌트 만들기
  - [x] 날짜 `day.js`로 파싱하여 보여주기
  - [x] 설명이 길 경우 말줄임표로 생략하기
- [x] localStorage의 데이터와 연동
- [x] 최신순 정렬
