### ISSUE TITLE
[수정] Todo 상태 select 디자인 변경

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/todo-list-with-vue#5]
### 개요
> Todo 상태를 나타내는 select 컴포넌트의 디자인을 변경한다.

### 해야 할 일
- [ ] select 다시 만들기
- [ ] 상태별 색깔 지정하기
- [ ] Todo 목록에 표시되는 상태 이름 바꾸기
